export type {
  DesktopJob,
  DesktopJobResult,
  JobLaunchResult,
  DiagnosticsSnapshot,
  LibraryAddRootRequest,
  LibraryAsset,
  LibraryDirectory,
  LibraryImportAssetsRequest,
  LibraryRemoveAssetsRequest,
  LibraryRoot,
  LibraryScanStatus,
  LibrarySearchRequest,
  LibrarySearchResult,
  LogEntry,
  ImportCueFileResult,
  ProjectSessionSnapshot,
  RelinkAssetResult,
  RunAnalysisRequest,
  RunExportRequest,
  RunPreviewRequest,
  SaveProjectRequest,
  StudioClient as DesktopApi
} from '@afterimage/studio-contracts';
